
package com.force.aus.soap;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidQueryLocatorFault", targetNamespace = "urn:fault.enterprise.soap.sforce.com")
public class InvalidQueryLocatorFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidQueryLocatorFault faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidQueryLocatorFault_Exception(String message, InvalidQueryLocatorFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidQueryLocatorFault_Exception(String message, InvalidQueryLocatorFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.force.aus.soap.InvalidQueryLocatorFault
     */
    public InvalidQueryLocatorFault getFaultInfo() {
        return faultInfo;
    }

}
